name: CI/CD for Strapi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upgrade npm
      run: npm install -g npm@latest

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-strapi-app .

    - name: Push Docker image to Docker Hub
      run: docker push my-strapi-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e

          # Update the package list and upgrade packages
          sudo apt update
          sudo apt upgrade -y

          # Install Docker if not installed
          if ! command -v docker &> /dev/null
          then
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi

          # Pull the latest Docker image
          docker pull my-strapi-app

          # Stop and remove any existing container named strapi
          if [ $(docker ps -q -f name=strapi) ]; then
            docker stop strapi
            docker rm strapi
          fi

          # Run the Docker container
          docker run -d -p 1337:1337 --name strapi my-strapi-app
